[build]
  publish = "frontend"
  command = "" # Leave blank for static sites, or use "npm run build" for frameworks

[dev]
  publish = "frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
